version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
      - dependencies
    ignore:
      - dependency-name: "node"
        versions: ["21.x"]
    commit-message:
      prefix: BAU
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
