name: DEV Post merge, deploy Docker build, ECR push, template copy to S3
on:
  push:
    branches:
      - main
  workflow_dispatch: # Deploy Manually

jobs:
  development:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: DEV
    name: ${{ matrix.environment }} docker build and push
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t deploy/template.yaml

      - name: "Push signed image to ECR, updated SAM template with image then upload it to the S3 Artifact Bucket"
        uses: govuk-one-login/devplatform-upload-action-ecr@1.2.0
        with:
          artifact-bucket-name: ${{ secrets[format('{0}_{1}', matrix.environment, 'ARTIFACT_BUCKET_NAME')] }}
          template-file: deploy/template.yaml
          working-directory: .
          docker-build-path: .
          role-to-assume-arn: ${{ secrets[format('{0}_{1}', matrix.environment, 'GH_ACTIONS_ROLE_ARN')] }}
          ecr-repo-name: ${{ secrets[format('{0}_{1}', matrix.environment, 'ECR_NAME_FRONT')] }}
